baseURL = 'https://gutibran.com'
languageCode = 'en-us'
title = "Brandon Gutierrez's web site"
enableGitInfo = false
tableOfContents = true
copyright = '© 2023 ABC Widgets, Inc.'

[markup]
  [markup.highlight]
    style = "xcode"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['$', '$'], ['\(', '\)']]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false
[params]
  math = true
  [params.images]
    resampleFilter = "Lanczos"
    quality = 85
    format = "webp"
  [params.author]
    email = 'bran09123@gmail.com'
    name = 'Brandon Gutierrez'

[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "gutibrans-blog"
  isHTML = false

[outputs]
  home = [ "HTML", "RSS" ]

[build]
  drafts = true
