baseURL = 'https://gutibran.com/'
languageCode = 'en-us'
title = 'gutibran.com'



[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.tableOfContents]
        endLevel = 6
        ordered = false
        startLevel = 1
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'nord'
        tabWidth = 4

[params]
  math = true